- name: Generate SSH key
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yaml
  vars:
    key_path: "{{ ssh_key_name }}/id_ed25519"

  tasks:
    - name: Create folder for temp SSH Key
      ansible.builtin.file:
        path: ~/tmp/{{ ssh_key_name }}
        state: directory
        mode: 0777
    - name: Generate SSH key
      become: true
      community.crypto.openssh_keypair:
        path: /home/{{ ansible_user_id }}/tmp/{{ key_path }}
        type: ed25519
        state: present
        mode: a=r
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
    - name: Create folder for target SSH Key
      ansible.builtin.file:
        path: ~/.ssh/{{ ssh_key_name }}
        state: directory
        mode: 0777
    - name: Copy SSH private key
      ansible.builtin.copy:
        src: ~/tmp/{{ key_path }}
        dest: ~/.ssh/{{ key_path }}
        mode: 0600
    - name: Copy SSH public key
      ansible.builtin.copy:
        src: ~/tmp/{{ key_path }}.pub
        dest: ~/.ssh/{{ key_path }}.pub
        mode: 0600
- name: Upload SSH key
  hosts: cluster
  vars_files:
    - vars/main.yaml
  vars:
    password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) }}"
    ssh_public_key_path: ~/.ssh/{{ ssh_key_name }}/id_ed25519.pub

  tasks:
    - name: Create deploy user
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        password: "{{ password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        groups: sudo
        append: true
    - name: Enable SSH key auth
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', ssh_public_key_path) }}"
