- name: Create new SSH
  hosts: cluster
  roles:
    - role: new-ssh-user
      vars:
        username: "{{ ansible_user }}"
        private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_user: vagrant
        ansible_ssh_pass: vagrant
        ansible_port: 22
