- name: My first playbook
  hosts: contabo
  become: true
  gather_facts: false
  vars:
    root_password: "123"

  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Hello world!"
    - name: Update Root user's Password
      ansible.builtin.user:
        name: root
        state: present
        password: "{{ root_password | password_hash('sha512') }}"
    - name: Enable Root SSH Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin yes"
        state: present
      notify:
        - Restart ssh
  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted
