- name: Kubernetes deployment
  hosts: cluster
  gather_facts: false
  tasks:
    - name: Create k8s resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'files/' + item) }}"
        wait: true
      with_items:
        - client-deployment.yml
        - client-service.yml
      delegate_to: localhost
    - name: Get hello-k8s service details.
      kubernetes.core.k8s_info:
        kind: Service
        name: client
        namespace: default
      register: svc
      delegate_to: localhost
    - name: Print the full svc variable.
      ansible.builtin.debug:
        var: svc
    - name: Set the service NodePort as a variable.
      ansible.builtin.set_fact:
        port: "{{ svc['resources'][0]['spec']['ports'][0]['nodePort'] }}"
        cluster_host: "{{ ansible_host }}"
    - name: Test a request to the service.
      ansible.builtin.uri:
        url: http://{{ cluster_host }}:{{ port }}
      delegate_to: localhost
    - name: Print the URL for hello-k8s.
      ansible.builtin.debug:
        msg: http://{{ cluster_host }}:{{ port }}
