- name: Kubernetes deployment
  hosts: cluster
  gather_facts: false
  tasks:
    - name: Set cluster host
      ansible.builtin.set_fact:
        cluster_host: "{{ ansible_host }}"
    - name: Create k8s resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'files/' + item) }}"
        wait: true
      with_items:
        - deployment.yml
        - service.yml
        - ingress-route.yaml
      delegate_to: localhost
    - name: Test a request to the service.
      ansible.builtin.uri:
        url: http://{{ cluster_host }}
      delegate_to: localhost
    - name: Print the URL for hello-k8s.
      ansible.builtin.debug:
        msg: http://{{ cluster_host }}
