- name: SSH Hardening
  hosts: cluster
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Download k3s install script
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: ~/k3s_install.sh
        mode: a+x
    - name: Execute k3s_install.sh
      become: true
      ansible.builtin.shell: ./k3s_install.sh >> ./k3s_install_log.txt
      args:
        chdir: "~"
        creates: k3s_install_log.txt
    - name: Fetch config
      become: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: true
    - name: Fix config host
      ansible.builtin.replace:
        path: ~/.kube/config
        regexp: "127.0.0.1"
        replace: "{{ inventory_hostname }}"
      delegate_to: 127.0.0.1
    - name: Fix config
      ansible.builtin.lineinfile:
        path: ~/.kube/config
        insertafter: "server: https"
        line: "    insecure-skip-tls-verify: false"
      delegate_to: 127.0.0.1
