- name: Create Kubernetes cluster
  hosts: cluster
  roles:
    - disable_swap
    - install_docker
    - role: install_k3s
      vars:
        local_kube_config: "{{ inventory_dir }}/.kube/config"
        k3s_version: v1.25.3+k3s1 # https://github.com/k3s-io/k3s/releases
        kubernetes_client_version: 25.3.0 # https://github.com/kubernetes-client/python/releases
    - deploy_kubernetes
